import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalPlansContextProvider } from "@/context/globalPlanContext";
import { ColumnMealContextProvider } from "@/context/columnMealContext";
import { TotalMacrosProvider } from "@/context/TotalMacrosContext";
import { PlanProvider } from "@/context/PlanContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <GlobalPlansContextProvider>
          <TotalMacrosProvider>
            <PlanProvider>
              <ColumnMealContextProvider>{children}</ColumnMealContextProvider>
            </PlanProvider>
          </TotalMacrosProvider>
        </GlobalPlansContextProvider>
      </body>
    </html>
  );
}
